apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: hello-auto
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: learn-gitop   # <-- แก้ให้ตรงชื่อ GitRepository ของคุณ
  git:
    checkout:
      ref:
        branch: main        # <-- แก้ให้ตรง branch ของคุณ
    commit:
      author:
        name: flux-bot
        email: bot@example.com
      messageTemplate: "chore: update hello image to {{range .Updated.Images}}{{.NewTag}}{{end}}"
    push:
      branch: main
  update:
    strategy: Setters
    path: ./clusters/my-cluster
