apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: hello
  namespace: flux-system
spec:
  image: ghcr.io/tanvanat/learn-gitop/hello
  interval: 1m
  secretRef:
    name: ghcr-credentials
